# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errortext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errortext', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='workTime',
            field=models.IntegerField(default=0, verbose_name='工作时间'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='beginTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machine',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='errortext',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.Machine'),
        ),
    ]
