# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20170717_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setName', models.CharField(max_length=200)),
            ],
        ),
    ]
