# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('compile_times', models.IntegerField(default=0)),
                ('last_compile', models.DateTimeField(auto_now=True)),
                ('run_times', models.IntegerField(default=0)),
                ('last_run', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
