# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0002_auto_20170824_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchinfo',
            name='last_compile',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='branchinfo',
            name='last_run',
            field=models.DateTimeField(null=True),
        ),
    ]
