# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserTest',
        ),
    ]
